//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace USP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(USP.Models.ViewModel.WebServiceGuideMetaData))]
    public partial class WebServiceGuide
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string GuideName { get; set; }
        public string DealDeptName { get; set; }
        public string DealAddress { get; set; }
        public string Contacts { get; set; }
        public string PhoneNumber { get; set; }
        public string DealTime { get; set; }
        public string BaseEstablishment { get; set; }
        public string EstablishmentCondition { get; set; }
        public string ApplicationMaterials { get; set; }
        public string ManagementProcess { get; set; }
        public string FlowChart { get; set; }
        public Nullable<long> BrowseCount { get; set; }
        public string Reserve { get; set; }
        public string Remark { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<long> Auditor { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<long> Canceler { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
    }
}
