//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class WebServiceGuideMetaData
    {
        [Required] 
        public virtual long ID
        {
            get;
            set;
        }
    	
        [StringLength(500, ErrorMessage="最多可输入500个字符")]
        public virtual string Title
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string GuideName
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string DealDeptName
        {
            get;
            set;
        }
    	
        [StringLength(500, ErrorMessage="最多可输入500个字符")]
        public virtual string DealAddress
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Contacts
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string PhoneNumber
        {
            get;
            set;
        }
    	
        [StringLength(500, ErrorMessage="最多可输入500个字符")]
        public virtual string DealTime
        {
            get;
            set;
        }
        public virtual string BaseEstablishment
        {
            get;
            set;
        }
        public virtual string EstablishmentCondition
        {
            get;
            set;
        }
        public virtual string ApplicationMaterials
        {
            get;
            set;
        }
        public virtual string ManagementProcess
        {
            get;
            set;
        }
        public virtual string FlowChart
        {
            get;
            set;
        }
        public virtual Nullable<long> BrowseCount
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Reserve
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        public virtual Nullable<long> Creator
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CreateTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Auditor
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> AuditTime
        {
            get;
            set;
        }
        public virtual Nullable<long> Canceler
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }
    }
}
