//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace USP.Models.ViewModel
{
    
    
    public class WebVediosMetaData
    {
        [Required]
        [Display(Name = "ID")]
        public virtual long ID
        {
            get;
            set;
        }
    	
        [StringLength(500, ErrorMessage="最多可输入500个字符")]
        [Display(Name ="视频标题")]
        public virtual string Title
        {
            get;
            set;
        }
        [Display(Name = "视频简介")]
        public virtual string Content
        {
            get;
            set;
        }
    	
        [StringLength(8000, ErrorMessage="最多可输入8000个字符")]
        [Display(Name = "视频URL")]
        public virtual string VedioUrl
        {
            get;
            set;
        }
    	
        [StringLength(8000, ErrorMessage="最多可输入8000个字符")]
        [Display(Name = "缩略图URL")]
        public virtual string PictureUrl
        {
            get;
            set;
        }
        [Display(Name = "播放次数")]
        public virtual Nullable<long> BrowerCount
        {
            get;
            set;
        }
    	
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        [Display(Name = "预留")]
        public virtual string Reserve
        {
            get;
            set;
        }
        [Display(Name = "备注")]
        [StringLength(250, ErrorMessage="最多可输入250个字符")]
        public virtual string Remark
        {
            get;
            set;
        }
        [Display(Name = "创建人")]
        public virtual Nullable<long> Creator
        {
            get;
            set;
        }
        [Display(Name = "创建时间")]
        public virtual Nullable<System.DateTime> CreateTime
        {
            get;
            set;
        }
        [Display(Name = "审批人")]
        public virtual Nullable<long> Auditor
        {
            get;
            set;
        }
        [Display(Name = "审批时间")]
        public virtual Nullable<System.DateTime> AuditTime
        {
            get;
            set;
        }
        [Display(Name = "注销人")]
        public virtual Nullable<long> Canceler
        {
            get;
            set;
        }
        [Display(Name = "注销时间")]
        public virtual Nullable<System.DateTime> CancelTime
        {
            get;
            set;
        }
    }
}
